- name: copying mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: installing mongodb-org
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: enable and start mongod
  ansible.builtin.service:
    name: mongod
    enabled: true
    state: started

- name: replacing 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: copying cotalogue.js
  ansible.builtin.copy:
    src: catalogue.js
    dest: /tmp

- name: loading catlogue.js
  ansible.builtin.shell: mongo --host mongodb.venkateshamsonnalia143.online </tmp/catalogue.js

- name: restarting mongodb
  ansible.builtin.service:
    name: mongod
    state: restarted