- name: Setup NodeJS repos
  ansible.builtin.shell: dnf module disable nodejs -y

- name: module enable nodejs:18
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: installing NodeJS
  ansilbe.builtin.yum:
    name: nodejs
    state: installed

- name: adding user roboshop
  ansible.builtin.user:
    name: roboshop

- name: creating app directory
  ansible.builtin.file:
    path: /app
    state: directory