- name: nodeJS Setup, adding user and repository
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs
- name: Downloading cart artifact
  ansible.builtin.unarchive:
    src: https://roboshop-builds.s3.amazonaws.com/cart.zip
    dest: /app
    remote_src: yes

- name: npm Installing
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: copying cart service
  ansible.builtin.copy:
    src: cart.service
    dest: /etc/systemd/system/cart.service

- name: Daemon-reload cart service
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: enabling and starting cart service
  ansible.builtin.service:
    name: cart
    enabled: true
    state: started